### PR TITLE
Explicitly delegate managedClasspath so that provided deps. are added to classpath

### LINKED ISSUE #34: Does not add provided dependencies to classpath
If a project contains some dependencies that are `provided` rather than in `compile` or `test` scope then they are not added to the `scapegoat:managedClasspath` resulting in compile failures.

`project/Dependencies.scala` (snippet)

```
// Scalactic utilities
  val scalactic = "org.scalactic" %% "scalactic" % scalatestVersion % "provided"

  val jodaTime = "joda-time" % "joda-time" % jodaTimeVersion
  val jodaConvert = "org.joda" % "joda-convert" % jodaConvertVersion
```

Output of `show scapegoat:managedClasspath`

```
[info] utils/scapegoat:managedClasspath
[info]  List(Attributed(/home/tim/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar), Attributed(/home/tim/.ivy2/cache/com.sksamuel.scapegoat/scalac-scapegoat-plugin_2.11/jars/scalac-scapegoat-plugin_2.11-1.0.0.jar), Attributed(/home/tim/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar), Attributed(/home/tim/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar), Attributed(/home/tim/.ivy2/cache/org.scaldi/scaldi_2.11/jars/scaldi_2.11-0.4.jar), Attributed(/home/tim/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.8.1.jar), Attributed(/home/tim/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.7.jar), Attributed(/home/tim/.ivy2/cache/org.clapper/grizzled-slf4j_2.11/jars/grizzled-slf4j_2.11-1.0.2.jar), Attributed(/home/tim/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.7.jar), Attributed(/home/tim/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.3.jar), Attributed(/home/tim/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.3.jar), Attributed(/home/tim/.ivy2/cache/org.codehaus.groovy/groovy/jars/groovy-2.4.3.jar))
[info] root/scapegoat:managedClasspath
[info]  List(Attributed(/home/tim/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar), Attributed(/home/tim/.ivy2/cache/com.sksamuel.scapegoat/scalac-scapegoat-plugin_2.11/jars/scalac-scapegoat-plugin_2.11-1.0.0.jar), Attributed(/home/tim/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar), Attributed(/home/tim/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar), Attributed(/home/tim/.ivy2/cache/org.scaldi/scaldi_2.11/jars/scaldi_2.11-0.4.jar))
```

Adding the (provided) dependency to the Scapegoat `libraryDependencies` also doe snot work:

```
libraryDependencies in Scapegoat ++= Seq(scalactic)
```

### PR DESCRIPTION
**Pull request by JoshRosen**
This patch fixes #34, an issue where provided dependencies were not added to the compile classpath when running the `scapegoat` task. There's probably a more principled way to fix this, but this is the minimal fix that worked for me.

### CODE REVIEW

File: src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala [hunk 1]
```diff
@@ -43,6 +43,8 @@ object ScapegoatSbtPlugin extends AutoPlugin {
       Defaults.compileSettings ++
       Seq(
         sources := (sources in Compile).value,
```
Comment (JoshRosen) [inline src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala]: @gregsymons, do you know why we need to explicitly set `sources` here? I see that you added this line in #24 when introducing the separate `scapegoat` task.

Based on my limited understanding of SBT configurations, I think that the intent behind the `val Scapegoat = config("scapegoat") extend Compile` further up in this file was that our `Scapegoat` configuration would inherit all of the `Compile` configuration's settings for settings which weren't explicitly defined. If that was the case, though, I guess we wouldn't need to explicitly define `sources` here. This kind of explains why I needed to also add explicit lines for `managedClasspath` and `unmanagedClasspath` in order to fix compilation with `provided` dependencies, but I wonder if there's a more principled fix that will implicitly inherit all of the undefined settings from `Compile` rather than forcing us to explicitly copy them here (I'm worried about leaving out other settings in a way that's confusing to users, e.g. leading to different compilation results).

Comment (sksamuel) [inline src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala]: My understanding is the same, that extending Compile should cause the task / setting lookup to propagate up the hierarchy. It might be because the scapegoat task is not scoped to the scapegoat config or something.

**Comment by sksamuel** [comment]
Thanks for the PR and keep up the good work on Spark - I use it extensively at Barclays.

File: src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala (hunk 1 above)
Comment (gregsymons) [inline src/main/scala/com/sksamuel/scapegoat/sbt/ScapegoatSbtPlugin.scala]: @JoshRosen The short answer is that it worked :smile: . But I think what happened is I made the same assumption you made (that inheriting Compile should have propagated the settings), but in practice that didn't seem to happen. I don't know that I searched terribly hard for a cleaner solution, though.
